name: Update Profile

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

permissions: {}

jobs:
  update-readme:
    name: Update Profile
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: Generate Bot Token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
          private-key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
          permission-contents: write

      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Bun
        uses: TimSchoenle/actions/actions/bun/setup-cached@e531be1a898653adee13a3c10b1ae4c1eb6487d0 # actions-bun-setup-cached-v1.1.3
        with:
          bun-version: latest

      - name: Generate README
        run: bun run generate-readme
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Commit and Push if changed
        id: auto-commit
        uses: TimSchoenle/actions/actions/common/commit-changes@85df1583f874da24a2de30e19280e031c25a09c5 # actions-common-commit-changes-v1.1.1
        with:
          commit_message: "docs: update readme"
          token: ${{ steps.generate_token.outputs.token }}
